//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace DUKCAPIL.asus_a43sj {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SIAKServicePortBinding", Namespace="http://service.siak.org/")]
    public partial class SIAKServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authKotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoKotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback authKelurahanOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoKTPKelurahanOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoBiodataKelurahanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SIAKServiceService() {
            this.Url = global::DUKCAPIL.Properties.Settings.Default.DUKCAPIL_asus_a43sj_SIAKServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authKotaCompletedEventHandler authKotaCompleted;
        
        /// <remarks/>
        public event infoKotaCompletedEventHandler infoKotaCompleted;
        
        /// <remarks/>
        public event authKelurahanCompletedEventHandler authKelurahanCompleted;
        
        /// <remarks/>
        public event infoKTPKelurahanCompletedEventHandler infoKTPKelurahanCompleted;
        
        /// <remarks/>
        public event infoBiodataKelurahanCompletedEventHandler infoBiodataKelurahanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.siak.org/", ResponseNamespace="http://service.siak.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kotaDummy authKota([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sandi) {
            object[] results = this.Invoke("authKota", new object[] {
                        username,
                        sandi});
            return ((kotaDummy)(results[0]));
        }
        
        /// <remarks/>
        public void authKotaAsync(string username, string sandi) {
            this.authKotaAsync(username, sandi, null);
        }
        
        /// <remarks/>
        public void authKotaAsync(string username, string sandi, object userState) {
            if ((this.authKotaOperationCompleted == null)) {
                this.authKotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthKotaOperationCompleted);
            }
            this.InvokeAsync("authKota", new object[] {
                        username,
                        sandi}, this.authKotaOperationCompleted, userState);
        }
        
        private void OnauthKotaOperationCompleted(object arg) {
            if ((this.authKotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authKotaCompleted(this, new authKotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.siak.org/", ResponseNamespace="http://service.siak.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public biodataPindahDummy[] infoKota([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int kotaID) {
            object[] results = this.Invoke("infoKota", new object[] {
                        kotaID});
            return ((biodataPindahDummy[])(results[0]));
        }
        
        /// <remarks/>
        public void infoKotaAsync(int kotaID) {
            this.infoKotaAsync(kotaID, null);
        }
        
        /// <remarks/>
        public void infoKotaAsync(int kotaID, object userState) {
            if ((this.infoKotaOperationCompleted == null)) {
                this.infoKotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoKotaOperationCompleted);
            }
            this.InvokeAsync("infoKota", new object[] {
                        kotaID}, this.infoKotaOperationCompleted, userState);
        }
        
        private void OninfoKotaOperationCompleted(object arg) {
            if ((this.infoKotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoKotaCompleted(this, new infoKotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.siak.org/", ResponseNamespace="http://service.siak.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kelurahanDummy authKelurahan([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sandi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string waktuString, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ipAddress) {
            object[] results = this.Invoke("authKelurahan", new object[] {
                        username,
                        sandi,
                        waktuString,
                        ipAddress});
            return ((kelurahanDummy)(results[0]));
        }
        
        /// <remarks/>
        public void authKelurahanAsync(string username, string sandi, string waktuString, string ipAddress) {
            this.authKelurahanAsync(username, sandi, waktuString, ipAddress, null);
        }
        
        /// <remarks/>
        public void authKelurahanAsync(string username, string sandi, string waktuString, string ipAddress, object userState) {
            if ((this.authKelurahanOperationCompleted == null)) {
                this.authKelurahanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthKelurahanOperationCompleted);
            }
            this.InvokeAsync("authKelurahan", new object[] {
                        username,
                        sandi,
                        waktuString,
                        ipAddress}, this.authKelurahanOperationCompleted, userState);
        }
        
        private void OnauthKelurahanOperationCompleted(object arg) {
            if ((this.authKelurahanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authKelurahanCompleted(this, new authKelurahanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.siak.org/", ResponseNamespace="http://service.siak.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public biodataKelurahanDummy[] infoKTPKelurahan([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int kelurahanID) {
            object[] results = this.Invoke("infoKTPKelurahan", new object[] {
                        kelurahanID});
            return ((biodataKelurahanDummy[])(results[0]));
        }
        
        /// <remarks/>
        public void infoKTPKelurahanAsync(int kelurahanID) {
            this.infoKTPKelurahanAsync(kelurahanID, null);
        }
        
        /// <remarks/>
        public void infoKTPKelurahanAsync(int kelurahanID, object userState) {
            if ((this.infoKTPKelurahanOperationCompleted == null)) {
                this.infoKTPKelurahanOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoKTPKelurahanOperationCompleted);
            }
            this.InvokeAsync("infoKTPKelurahan", new object[] {
                        kelurahanID}, this.infoKTPKelurahanOperationCompleted, userState);
        }
        
        private void OninfoKTPKelurahanOperationCompleted(object arg) {
            if ((this.infoKTPKelurahanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoKTPKelurahanCompleted(this, new infoKTPKelurahanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.siak.org/", ResponseNamespace="http://service.siak.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public biodataKelurahanDummy[] infoBiodataKelurahan([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int kelurahanID) {
            object[] results = this.Invoke("infoBiodataKelurahan", new object[] {
                        kelurahanID});
            return ((biodataKelurahanDummy[])(results[0]));
        }
        
        /// <remarks/>
        public void infoBiodataKelurahanAsync(int kelurahanID) {
            this.infoBiodataKelurahanAsync(kelurahanID, null);
        }
        
        /// <remarks/>
        public void infoBiodataKelurahanAsync(int kelurahanID, object userState) {
            if ((this.infoBiodataKelurahanOperationCompleted == null)) {
                this.infoBiodataKelurahanOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoBiodataKelurahanOperationCompleted);
            }
            this.InvokeAsync("infoBiodataKelurahan", new object[] {
                        kelurahanID}, this.infoBiodataKelurahanOperationCompleted, userState);
        }
        
        private void OninfoBiodataKelurahanOperationCompleted(object arg) {
            if ((this.infoBiodataKelurahanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoBiodataKelurahanCompleted(this, new infoBiodataKelurahanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.siak.org/")]
    public partial class kotaDummy {
        
        private int kotaIDField;
        
        private string namaKotaField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kotaID {
            get {
                return this.kotaIDField;
            }
            set {
                this.kotaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string namaKota {
            get {
                return this.namaKotaField;
            }
            set {
                this.namaKotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.siak.org/")]
    public partial class biodataKelurahanDummy {
        
        private string agamaField;
        
        private string alamatField;
        
        private string expiredKTPField;
        
        private byte[] fotoField;
        
        private string jenisKelaminField;
        
        private string namaField;
        
        private string nikField;
        
        private string noTeleponField;
        
        private string pekerjaanField;
        
        private string pendidikanField;
        
        private string tanggalLahirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agama {
            get {
                return this.agamaField;
            }
            set {
                this.agamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                this.alamatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string expiredKTP {
            get {
                return this.expiredKTPField;
            }
            set {
                this.expiredKTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jenisKelamin {
            get {
                return this.jenisKelaminField;
            }
            set {
                this.jenisKelaminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                this.namaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nik {
            get {
                return this.nikField;
            }
            set {
                this.nikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noTelepon {
            get {
                return this.noTeleponField;
            }
            set {
                this.noTeleponField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pekerjaan {
            get {
                return this.pekerjaanField;
            }
            set {
                this.pekerjaanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pendidikan {
            get {
                return this.pendidikanField;
            }
            set {
                this.pendidikanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tanggalLahir {
            get {
                return this.tanggalLahirField;
            }
            set {
                this.tanggalLahirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.siak.org/")]
    public partial class kelurahanDummy {
        
        private int kelurahanIDField;
        
        private string sandiField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kelurahanID {
            get {
                return this.kelurahanIDField;
            }
            set {
                this.kelurahanIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sandi {
            get {
                return this.sandiField;
            }
            set {
                this.sandiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.siak.org/")]
    public partial class biodataPindahDummy {
        
        private string agamaField;
        
        private string alamatField;
        
        private byte[] fotoField;
        
        private string jenisKelaminField;
        
        private string namaField;
        
        private string nikField;
        
        private string noTeleponField;
        
        private string pekerjaanField;
        
        private string pendidikanField;
        
        private string tanggalLahirField;
        
        private string tanggalPengajuanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agama {
            get {
                return this.agamaField;
            }
            set {
                this.agamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                this.alamatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jenisKelamin {
            get {
                return this.jenisKelaminField;
            }
            set {
                this.jenisKelaminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                this.namaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nik {
            get {
                return this.nikField;
            }
            set {
                this.nikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noTelepon {
            get {
                return this.noTeleponField;
            }
            set {
                this.noTeleponField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pekerjaan {
            get {
                return this.pekerjaanField;
            }
            set {
                this.pekerjaanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pendidikan {
            get {
                return this.pendidikanField;
            }
            set {
                this.pendidikanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tanggalLahir {
            get {
                return this.tanggalLahirField;
            }
            set {
                this.tanggalLahirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tanggalPengajuan {
            get {
                return this.tanggalPengajuanField;
            }
            set {
                this.tanggalPengajuanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void authKotaCompletedEventHandler(object sender, authKotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authKotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authKotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public kotaDummy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((kotaDummy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void infoKotaCompletedEventHandler(object sender, infoKotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoKotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoKotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public biodataPindahDummy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((biodataPindahDummy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void authKelurahanCompletedEventHandler(object sender, authKelurahanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authKelurahanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authKelurahanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public kelurahanDummy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((kelurahanDummy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void infoKTPKelurahanCompletedEventHandler(object sender, infoKTPKelurahanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoKTPKelurahanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoKTPKelurahanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public biodataKelurahanDummy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((biodataKelurahanDummy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void infoBiodataKelurahanCompletedEventHandler(object sender, infoBiodataKelurahanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoBiodataKelurahanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoBiodataKelurahanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public biodataKelurahanDummy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((biodataKelurahanDummy[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591